# 1. runs-on
# 2. CE EE

name: Add New Release to Pongo

on:
  release:
    types: [published]
  push:
    tags:
    # CE
    - '[1-9]+.[0-9]+.[0-9]+'
    # EE
    - '[1-9]+.[0-9]+.[0-9]+.[0-9]+'

env:
  CODE_BASE: EE

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.set_tag.outputs.TAG_NAME }}
    steps:
    - name: Set Release Tag
      id: set_tag
      shell: bash
      run: |
        echo "github.event.name = ${{ github.event_name }}"
        echo "github.ref = ${{ github.ref }}"
        echo "github.ref_name = ${{ github.ref_name }}"
        echo "github.event.release.tag_name = ${{ github.event.release.tag_name }}"

        if [[ "${{ github.event_name }}" == "push" ]] ; then
          echo "TAG_NAME=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ github.event_name }}" == "release" ]] ; then
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
        fi
  add_release_to_pongo:
    runs-on: ubuntu-latest
    needs:
    - get_tag
    steps:
    - name: Checkout Kong Repo
      id: checkout_kong_repo
      uses: actions/checkout@v4
      with:
        # token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
        ref: ${{ needs.get_tag.outputs.tag_version }}
        path: kong
    - name: Checkout Pongo Repo
      id: checkout_pongo_repo
      uses: actions/checkout@v4
      with:
        repository: kong/kong-pongo
        ref: master
        path: kong-pongo
    - name: Create Pongo PR
      id: create_pongo_pr
      env:
        # Required by Pongo 'assets/update_versions.sh' to clone 'kong/kong' or 'kong/kong-ee'
        # GITHUB_TOKEN: ${{ secrets.PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        ls -lrta "$PWD"
        cd kong; git status; cd ..

        # git config
        git config --global user.email "ci-bot@konghq.com"
        git config --global user.name "CI Bot"

        # create branch
        cd kong-pongo
        git checkout -b "add-${CODE_BASE,,}-version-${{ needs.get_tag.outputs.tag_version }}"
        git status

        # update version
        VERSIONS_FILE="assets/kong_${CODE_BASE}_versions.ver"
        if [[ ! -f $VERSIONS_FILE ]]; then
          echo "Versions file '$VERSIONS_FILE' not found"
          exit 1
        fi
        echo "${{ needs.get_tag.outputs.tag_version }}" >> "$VERSIONS_FILE"
        sort --version-sort -o "$VERSIONS_FILE" "$VERSIONS_FILE"
        git diff
        git add "$VERSIONS_FILE"
        git commit -m "feat(version): add Kong ${CODE_BASE} version $ADD_VERSION"
        git status

        # update artifacts
