name: Add New Release to Pongo

on:
  release:
    types: [published]
  push:
    tags:
    # CE
    - '[1-9]+.[0-9]+.[0-9]+'
    # EE
    - '[1-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  add_to_pongo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Pongo Repo
      id: checkout_pongo_repo
      uses: actions/checkout@v4
      with:
        repository: kong/kong-pongo
        ref: master
        path: kong-pongo-test
        # Pongo is a public repo, secret is optional
        # token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
    - name: Create Pongo PR
      id: create_pongo_pr
      env:
        # Required by Pongo 'assets/update_versions.sh' to clone 'kong/kong' or 'kong/kong-ee'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$PWD"
