# to-dos:
#   1. cover community PRs.

name: Notify CE2EE on PR merge
on:
  pull_request:
    types: [closed, labeled, unlabeled]

jobs:
  check_label:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    steps:
    - id: check
      uses: actions/github-script@v6
      with:
        script: |
          const labels = context.payload.pull_request.labels.map(l => l.name)
          return !labels.includes('skip-cherry-pick')

  notify_actor:
    needs: check_label
    if: ${{ github.event.pull_request.merged == true && needs.check_label.outputs.exists == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Generate Slack Payload
      id: gen_slack_payload
      uses: actions/github-script@v6
      env:
        SLACK_CHANNEL: gateway-notifications
        SLACK_MAPPING: "${{ vars.GH_ID_2_SLACK_ID_MAPPING }}"
      with:
        script: |
          const pr = context.payload.pull_request;
          const slack_mapping = JSON.parse(env.SLACK_MAPPING);
          const actor_github_id = "${{ github.event.workflow_run.actor.login }}";
          const actor_slack_id = slack_mapping[actor_github_id];
          const actor = actor_slack_id ? `<@${actor_slack_id}>` : actor_github_id;

          const payload = {
            text: "${actor}, PR #pr.number - 'pr.title' was merged. Please cherry-pick to EE or label 'skip-cherry-pick'. View it here: pr.html_url.",
            channel: "env.SLACK_CHANNEL",
          };

          return JSON.stringify(payload);
        result-encoding: string

    - name: Send Slack Message
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: ${{ steps.gen_slack_payload.outputs.result }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GATEWAY_NOTIFICATIONS_WEBHOOK }}